"""subscriptions

Revision ID: b636dbb79953
Revises: fd78677870c3
Create Date: 2018-07-14 08:26:07.919155

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b636dbb79953'
down_revision = 'fd78677870c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscriptions',
    sa.Column('subscriber_id', sa.Integer(), nullable=True),
    sa.Column('feed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['feed_id'], ['feed.id'], ),
    sa.ForeignKeyConstraint(['subscriber_id'], ['user.id'], )
    )
    op.drop_index('ix_subscription_feed_id', table_name='subscription')
    op.drop_index('ix_subscription_subscriber_id', table_name='subscription')
    op.drop_table('subscription')
    op.drop_table('student')
    op.drop_table('professor')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('professor',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('student',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subscription',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('subscriber_id', sa.INTEGER(), nullable=True),
    sa.Column('feed_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['feed_id'], ['feed.id'], ),
    sa.ForeignKeyConstraint(['subscriber_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_subscription_subscriber_id', 'subscription', ['subscriber_id'], unique=False)
    op.create_index('ix_subscription_feed_id', 'subscription', ['feed_id'], unique=False)
    op.drop_table('subscriptions')
    # ### end Alembic commands ###
