"""empty message

Revision ID: b7fb0fbc5aed
Revises: 
Create Date: 2018-07-14 13:55:07.475202

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7fb0fbc5aed'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=10), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('about_me', sa.String(length=140), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('feed',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feed_name'), 'feed', ['name'], unique=False)
    op.create_index(op.f('ix_feed_owner_id'), 'feed', ['owner_id'], unique=False)
    op.create_table('event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('feed_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=120), nullable=True),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.Column('start_day', sa.DateTime(), nullable=True),
    sa.Column('start_month', sa.DateTime(), nullable=True),
    sa.Column('end_day', sa.DateTime(), nullable=True),
    sa.Column('end_month', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['feed_id'], ['feed.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('description'),
    sa.UniqueConstraint('title')
    )
    op.create_index(op.f('ix_event_end_day'), 'event', ['end_day'], unique=False)
    op.create_index(op.f('ix_event_end_month'), 'event', ['end_month'], unique=False)
    op.create_index(op.f('ix_event_feed_id'), 'event', ['feed_id'], unique=False)
    op.create_index(op.f('ix_event_start_day'), 'event', ['start_day'], unique=False)
    op.create_index(op.f('ix_event_start_month'), 'event', ['start_month'], unique=False)
    op.create_table('subscribers',
    sa.Column('subscriber_id', sa.Integer(), nullable=True),
    sa.Column('feed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['feed_id'], ['feed.id'], ),
    sa.ForeignKeyConstraint(['subscriber_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subscribers')
    op.drop_index(op.f('ix_event_start_month'), table_name='event')
    op.drop_index(op.f('ix_event_start_day'), table_name='event')
    op.drop_index(op.f('ix_event_feed_id'), table_name='event')
    op.drop_index(op.f('ix_event_end_month'), table_name='event')
    op.drop_index(op.f('ix_event_end_day'), table_name='event')
    op.drop_table('event')
    op.drop_index(op.f('ix_feed_owner_id'), table_name='feed')
    op.drop_index(op.f('ix_feed_name'), table_name='feed')
    op.drop_table('feed')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
